# Generated by Django 4.1.13 on 2026-01-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('funding_type', models.CharField(choices=[('mortgage', 'Mortgage Finance'), ('senior_debt', 'Senior Debt/Development Finance'), ('equity', 'Equity Finance')], max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('industrial', 'Industrial')], max_length=20)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_min_months', models.PositiveIntegerField()),
                ('term_max_months', models.PositiveIntegerField()),
                ('max_ltv_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_structure', models.CharField(choices=[('interest_only', 'Interest‑Only'), ('amortising', 'Amortising')], max_length=20)),
                ('fees', models.JSONField(blank=True, default=dict)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lenders.lenderprofile')),
            ],
        ),
    ]
