# Generated by Django 4.1.13 on 2026-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='funding_type',
            field=models.CharField(choices=[('development_finance', 'Development Finance'), ('senior_debt', 'Senior Debt/Development Finance'), ('commercial_mortgage', 'Commercial Mortgages'), ('mortgage', 'Mortgage Finance'), ('equity', 'Equity Finance'), ('revenue_based', 'Revenue Based Funding'), ('merchant_cash_advance', 'Merchant Cash Advance'), ('term_loan_p2p', 'Term Loans (Peer-to-Peer)'), ('bank_overdraft', 'Bank Overdraft'), ('business_credit_card', 'Business Credit Cards'), ('ip_funding', 'Intellectual Property (IP) Funding'), ('stock_finance', 'Stock Finance'), ('asset_finance', 'Asset Finance'), ('factoring', 'Factoring / Invoice Discounting'), ('trade_finance', 'Trade Finance'), ('export_finance', 'Export Finance'), ('public_sector_startup', 'Public Sector Funding (Start Up Loan)')], max_length=30),
        ),
    ]
