# Generated by Django 4.1.13 on 2026-01-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_funding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('industrial', 'Industrial'), ('n/a', 'N/A - Not Applicable')], help_text='Not required for non-property funding types', max_length=20, null=True),
        ),
    ]
