# Generated by Django 4.1.13 on 2026-01-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
        ('projects', '0006_alter_project_term_required_months'),
        ('products', '0003_alter_product_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='fees',
        ),
        migrations.AlterField(
            model_name='product',
            name='funding_type',
            field=models.CharField(choices=[('development_finance', 'Development Finance'), ('senior_debt', 'Senior Debt/Development Finance'), ('commercial_mortgage', 'Commercial Mortgages'), ('mortgage', 'Mortgage Finance'), ('equity', 'Equity Finance'), ('revenue_based', 'Revenue Based Funding'), ('merchant_cash_advance', 'Merchant Cash Advance'), ('term_loan_p2p', 'Term Loans (Peer-to-Peer)'), ('bank_overdraft', 'Bank Overdraft'), ('business_credit_card', 'Business Credit Cards'), ('ip_funding', 'Intellectual Property (IP) Funding'), ('stock_finance', 'Stock Finance'), ('asset_finance', 'Asset Finance'), ('factoring', 'Factoring / Invoice Discounting'), ('trade_finance', 'Trade Finance'), ('export_finance', 'Export Finance'), ('public_sector_startup', 'Public Sector Funding (Start Up Loan)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('industrial', 'Industrial'), ('n/a', 'N/A - Not Applicable')], default='n/a', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FavouriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Borrower's notes about this product")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(help_text='Borrower who favourited this product', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='borrowers.borrowerprofile')),
                ('product', models.ForeignKey(help_text='Product that was favourited', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='products.product')),
                ('project', models.ForeignKey(blank=True, help_text='Project this product was matched for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='projects.project')),
            ],
            options={
                'verbose_name': 'Favourite Product',
                'verbose_name_plural': 'Favourite Products',
                'ordering': ['-created_at'],
                'unique_together': {('borrower', 'product', 'project')},
            },
        ),
    ]
