# Generated by Django 4.1.13 on 2026-01-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_step', models.CharField(blank=True, max_length=50)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_complete', models.BooleanField(default=False)),
                ('contact_complete', models.BooleanField(default=False)),
                ('company_complete', models.BooleanField(default=False)),
                ('address_complete', models.BooleanField(default=False)),
                ('financial_complete', models.BooleanField(default=False)),
                ('documents_complete', models.BooleanField(default=False)),
                ('company_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('verification_score', models.IntegerField(blank=True, help_text='Overall verification score (0-100)', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Progress',
            },
        ),
        migrations.CreateModel(
            name='OnboardingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('national_insurance_number', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('address_line_3', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('address_verification_data', models.JSONField(blank=True, default=dict)),
                ('address_verified_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_registration_number', models.CharField(blank=True, max_length=50)),
                ('company_type', models.CharField(blank=True, max_length=50)),
                ('company_status', models.CharField(blank=True, max_length=50)),
                ('company_incorporation_date', models.DateField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True)),
                ('company_verification_data', models.JSONField(blank=True, default=dict)),
                ('company_verified_at', models.DateTimeField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('director_date_of_birth', models.DateField(blank=True, null=True)),
                ('director_nationality', models.CharField(blank=True, max_length=100)),
                ('director_verification_data', models.JSONField(blank=True, default=dict)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('employment_company', models.CharField(blank=True, max_length=200)),
                ('employment_position', models.CharField(blank=True, max_length=200)),
                ('years_in_employment', models.IntegerField(blank=True, null=True)),
                ('source_of_funds', models.TextField(blank=True)),
                ('existing_debts', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('previous_projects', models.IntegerField(blank=True, null=True)),
                ('risk_tolerance', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_collected_via', models.CharField(default='chatbot', max_length=20)),
                ('documents_uploaded', models.ManyToManyField(blank=True, to='documents.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Data',
            },
        ),
    ]
