# Generated by Django 4.1.13 on 2026-01-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='directors_data',
            field=models.JSONField(blank=True, default=list, help_text='List of directors with name, DOB, nationality, and verification data'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='fca_permissions',
            field=models.TextField(blank=True, help_text='FCA permissions held'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='fca_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='financial_licences',
            field=models.TextField(blank=True, help_text='Other financial licences held'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='has_fca_registration',
            field=models.BooleanField(default=False, help_text='Whether organisation has FCA registration'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='key_personnel',
            field=models.TextField(blank=True, help_text='Key personnel names and positions'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='lending_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total lending capacity', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='regulatory_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regulatory capital requirement', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of assets', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='source_of_funds',
            field=models.TextField(blank=True, help_text='Source of funds for loan application or lending'),
        ),
    ]
