# Generated by Django 4.1.13 on 2026-01-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingdata_directors_data_onboardingdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='assets_investments',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of investments', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='assets_liabilities_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete asset and liability statement data'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='assets_other',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of other assets', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='assets_real_estate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of real estate assets', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='liabilities_loans',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of loans', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='liabilities_mortgages',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of mortgages', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='liabilities_other',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of other liabilities', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='portfolio_description',
            field=models.TextField(blank=True, help_text='Description of current property portfolio or business assets'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='portfolio_property_details',
            field=models.TextField(blank=True, help_text='Detailed property portfolio information'),
        ),
    ]
