# Generated by Django 4.1.13 on 2026-01-09 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documenttype_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_application_borrower_consent_given_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(help_text='Firm or company name', max_length=200)),
                ('trading_name', models.CharField(blank=True, help_text='Trading name if different', max_length=200)),
                ('company_registration_number', models.CharField(blank=True, max_length=50)),
                ('services_offered', models.JSONField(default=list, help_text='List of services offered: monitoring_surveyor, valuation, solicitor, other')),
                ('primary_service', models.CharField(choices=[('monitoring_surveyor', 'Monitoring Surveyor'), ('valuation', 'Valuation'), ('solicitor', 'Solicitor'), ('other', 'Other Professional Service')], help_text='Primary service type', max_length=30)),
                ('qualifications', models.JSONField(default=list, help_text='List of professional qualifications (RICS, SRA, CILEX, etc.)')),
                ('professional_registration_numbers', models.JSONField(blank=True, default=dict, help_text='Professional registration numbers (e.g., RICS number, SRA number)')),
                ('insurance_details', models.JSONField(blank=True, default=dict, help_text='Professional indemnity insurance details')),
                ('compliance_certifications', models.JSONField(blank=True, default=list, help_text='Compliance certifications (ISO, FCA, etc.)')),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('geographic_coverage', models.JSONField(blank=True, default=list, help_text='Regions/counties where services are offered')),
                ('service_description', models.TextField(blank=True, help_text='Description of services offered')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('key_personnel', models.JSONField(blank=True, default=list, help_text='Key personnel with qualifications and experience')),
                ('current_capacity', models.PositiveIntegerField(default=10, help_text='Current number of active projects')),
                ('max_capacity', models.PositiveIntegerField(default=20, help_text='Maximum number of concurrent projects')),
                ('average_response_time_days', models.PositiveIntegerField(default=3, help_text='Average response time in days')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, to='documents.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Profile',
                'verbose_name_plural': 'Consultant Profiles',
            },
        ),
        migrations.CreateModel(
            name='ConsultantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('monitoring_surveyor', 'Monitoring Surveyor'), ('valuation', 'Valuation'), ('solicitor', 'Solicitor')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Specific requirements for this service')),
                ('required_by_date', models.DateField(blank=True, help_text='Required completion date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting Quotes'), ('quotes_received', 'Quotes Received'), ('consultant_selected', 'Consultant Selected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('required_qualifications', models.JSONField(blank=True, default=list, help_text='Required qualifications (e.g., RICS, SRA)')),
                ('geographic_requirement', models.CharField(blank=True, help_text='Required geographic location', max_length=100)),
                ('minimum_experience_years', models.PositiveIntegerField(blank=True, help_text='Minimum years of experience required', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='The loan application requiring this service', on_delete=django.db.models.deletion.CASCADE, related_name='consultant_services', to='applications.application')),
            ],
            options={
                'verbose_name': 'Consultant Service',
                'verbose_name_plural': 'Consultant Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_amount', models.DecimalField(decimal_places=2, help_text='Total quote amount in GBP', max_digits=15)),
                ('quote_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of quote (e.g., fees, expenses, VAT)')),
                ('estimated_completion_date', models.DateField(help_text='Estimated date of service completion')),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and schedule')),
                ('service_description', models.TextField(blank=True, help_text='Detailed description of services to be provided')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverables')),
                ('timeline', models.TextField(blank=True, help_text='Proposed timeline for service delivery')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions of the quote')),
                ('validity_period_days', models.PositiveIntegerField(default=30, help_text='Quote validity period in days')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or comments')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='consultants.consultantprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='consultants.consultantservice')),
            ],
            options={
                'verbose_name': 'Consultant Quote',
                'verbose_name_plural': 'Consultant Quotes',
                'ordering': ['-submitted_at'],
                'unique_together': {('consultant', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ConsultantAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True, help_text='Date when consultant was appointed')),
                ('start_date', models.DateField(blank=True, help_text='Actual start date of service', null=True)),
                ('expected_completion_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('status', models.CharField(choices=[('appointed', 'Appointed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='appointed', max_length=30)),
                ('progress_notes', models.JSONField(blank=True, default=list, help_text='Progress notes and updates from consultant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultants.consultantprofile')),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents uploaded by consultant', related_name='consultant_appointments', to='documents.document')),
                ('quote', models.OneToOneField(help_text='The quote that was accepted', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='consultants.consultantquote')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='consultants.consultantservice')),
            ],
            options={
                'verbose_name': 'Consultant Appointment',
                'verbose_name_plural': 'Consultant Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
