# Generated by Django 4.1.13 on 2026-01-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(choices=[('revenue_based', 'Revenue Based Funding'), ('merchant_cash_advance', 'Merchant Cash Advance'), ('term_loan_p2p', 'Term Loans (Peer-to-Peer)'), ('bank_overdraft', 'Bank Overdraft'), ('business_credit_card', 'Business Credit Cards'), ('ip_funding', 'Intellectual Property (IP) Funding'), ('stock_finance', 'Stock Finance'), ('asset_finance', 'Asset Finance'), ('factoring', 'Factoring / Invoice Discounting'), ('trade_finance', 'Trade Finance'), ('export_finance', 'Export Finance'), ('public_sector_startup', 'Public Sector Funding (Start Up Loan)')], max_length=30)),
                ('request_reference', models.CharField(blank=True, help_text='Unique identifier for this funding request', max_length=10, null=True, unique=True)),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('term_required_months', models.PositiveIntegerField(blank=True, null=True)),
                ('purpose', models.TextField(help_text='Purpose of the funding')),
                ('description', models.TextField(blank=True)),
                ('funding_specific_data', models.JSONField(blank=True, default=dict, help_text='Additional data specific to the funding type (e.g., revenue for revenue-based, IP details for IP funding)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='borrowers.borrowerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
