# Generated by Django 4.1.13 on 2026-01-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('identity', 'Identity Verification'), ('address', 'Address Verification'), ('financial', 'Financial Documents'), ('company', 'Company Documents'), ('property', 'Property Documents'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_for_loan_types', models.JSONField(default=list, help_text="List of loan types this document is required for (e.g., ['business_finance', 'construction_finance'])")),
                ('is_required', models.BooleanField(default=False, help_text='Whether this document is mandatory')),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='Maximum file size in MB')),
                ('allowed_file_types', models.JSONField(default=list, help_text="List of allowed MIME types (e.g., ['application/pdf', 'image/jpeg'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='ai_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='AI assessment results including risk score, key findings, recommendations'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(blank=True, help_text='File content (for small files only)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Notes from validation process'),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_score',
            field=models.IntegerField(blank=True, help_text='Validation score (0-100) based on file quality, format, completeness', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Validation Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Type of document (e.g., Bank Statement, ID, Company Accounts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype'),
        ),
    ]
