# Generated by Django 4.1.13 on 2026-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Borrower', 'Borrower'), ('Lender', 'Lender'), ('Consultant', 'Consultant'), ('Admin', 'Admin')], max_length=20, unique=True),
        ),
    ]
