"""Models for underwriting reports.

The `UnderwritingReport` model stores AI‑generated underwriting
reports produced via the OpenAI ChatGPT API.  Each report is
associated with a project and optionally a lender or borrower
profile depending on the report type.  Reports can be reused
across multiple sessions and audited by the admin.
"""

from __future__ import annotations

from django.db import models

from borrowers.models import BorrowerProfile
from lenders.models import LenderProfile
from projects.models import Project


class UnderwritingReport(models.Model):
    """Represents an underwriting report generated by AI."""

    REPORT_TYPES = [
        ("borrower", "Borrower"),
        ("lender", "Lender"),
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="underwriting_reports")
    borrower = models.ForeignKey(BorrowerProfile, on_delete=models.SET_NULL, null=True, blank=True)
    lender = models.ForeignKey(LenderProfile, on_delete=models.SET_NULL, null=True, blank=True)
    report_type = models.CharField(max_length=20, choices=REPORT_TYPES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:  # pragma: no cover
        return f"UnderwritingReport(type={self.report_type}, project_id={self.project_id})"