# Generated by Django 4.1.13 on 2026-01-09 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_equity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCASelfCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_type', models.CharField(choices=[('sophisticated', 'Sophisticated Investor'), ('high_net_worth', 'High Net Worth Individual'), ('restricted', 'Restricted Investor'), ('certified', 'Certified Sophisticated Investor')], help_text='Type of FCA self-certification', max_length=50)),
                ('is_high_net_worth', models.BooleanField(default=False, help_text='I confirm I am a high net worth individual (annual income > £100k or net assets > £250k)')),
                ('is_sophisticated', models.BooleanField(default=False, help_text='I confirm I am a sophisticated investor with knowledge and experience in unlisted securities')),
                ('understands_risks', models.BooleanField(default=False, help_text='I understand that investments in unlisted securities carry significant risks')),
                ('understands_illiquidity', models.BooleanField(default=False, help_text='I understand that these investments may be difficult to sell and may lose value')),
                ('can_afford_loss', models.BooleanField(default=False, help_text='I can afford to lose my entire investment without affecting my standard of living')),
                ('has_received_advice', models.BooleanField(default=False, help_text='I have received appropriate advice or have sufficient experience to make this decision')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, help_text='Annual income in GBP (optional, for high net worth certification)', max_digits=15, null=True)),
                ('net_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Net assets in GBP (optional, for high net worth certification)', max_digits=15, null=True)),
                ('investment_experience_years', models.IntegerField(blank=True, help_text='Years of investment experience (optional)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which certification was submitted', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from browser')),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this certification is currently active')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (not visible to user)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fca_certification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCA Self-Certification',
                'verbose_name_plural': 'FCA Self-Certifications',
                'ordering': ['-certified_at'],
            },
        ),
    ]
