# Generated by Django 4.1.13 on 2026-01-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('company_number', models.CharField(blank=True, max_length=50)),
                ('fca_registration_number', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('company_story', models.TextField(blank=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('financial_licences', models.CharField(blank=True, max_length=255)),
                ('membership_bodies', models.CharField(blank=True, max_length=255)),
                ('key_personnel', models.JSONField(blank=True, default=list)),
                ('risk_compliance_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, to='documents.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
