# Generated by Django 4.1.13 on 2026-01-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(choices=[('mortgage', 'Mortgage Finance'), ('senior_debt', 'Senior Debt/Development Finance'), ('equity', 'Equity Finance')], max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('industrial', 'Industrial')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('development_extent', models.CharField(choices=[('light_refurb', 'Light Refurb'), ('heavy_refurb', 'Heavy Refurb'), ('conversion', 'Conversion'), ('new_build', 'New Build')], max_length=20)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=20)),
                ('planning_permission', models.BooleanField(default=False)),
                ('planning_authority', models.CharField(blank=True, max_length=100)),
                ('planning_reference', models.CharField(blank=True, max_length=100)),
                ('planning_description', models.TextField(blank=True)),
                ('loan_amount_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('term_required_months', models.PositiveIntegerField()),
                ('repayment_method', models.CharField(choices=[('sale', 'Sale'), ('refinance', 'Refinance')], max_length=20)),
                ('unit_counts', models.JSONField(default=dict)),
                ('gross_internal_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('build_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_development_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funds_provided_by_applicant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=255)),
                ('existing_mortgage', models.BooleanField(default=False)),
                ('mortgage_company', models.CharField(blank=True, max_length=100)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='borrowers.borrowerprofile')),
            ],
        ),
    ]
