# Generated by Django 4.1.13 on 2026-01-09 15:54

from django.db import migrations, models
import random
import string


def generate_reference():
    """Generate a unique 6-character alphanumeric reference."""
    chars = string.ascii_uppercase.replace('I', '').replace('O', '') + '23456789'
    return ''.join(random.choices(chars, k=6))


def populate_initial_references(apps, schema_editor):
    """Populate project_reference for existing projects before adding unique constraint."""
    Project = apps.get_model('projects', 'Project')
    existing_refs = set()
    
    for project in Project.objects.all():
        max_attempts = 100
        for _ in range(max_attempts):
            ref = generate_reference()
            if ref not in existing_refs:
                project.project_reference = ref
                project.save(update_fields=['project_reference'])
                existing_refs.add(ref)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        # Step 1: Add field as nullable and non-unique first
        migrations.AddField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, null=True, help_text='Unique short identifier for this project (auto-generated)', max_length=6),
        ),
        # Step 2: Populate existing projects with references
        migrations.RunPython(populate_initial_references, migrations.RunPython.noop),
        # Step 3: Make it unique and non-nullable
        migrations.AlterField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, null=True, help_text='Unique short identifier for this project (auto-generated)', max_length=6, unique=True),
        ),
    ]
