# Generated by Django 4.1.13 on 2026-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_populate_project_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, help_text='Unique short identifier for this project (auto-generated)', max_length=6, null=True, unique=True),
        ),
    ]
