# Generated by Django 4.1.13 on 2026-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_funding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='term_required_months',
            field=models.PositiveIntegerField(blank=True, help_text='Optional for some funding types', null=True),
        ),
    ]
