# Generated by Django 4.1.13 on 2026-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='initiated_by',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], default='lender', help_text='Whether this application was initiated by the borrower (enquiry) or lender (offer)', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposed_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposed_ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
