# Generated by Django 4.1.13 on 2026-01-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_application_initiated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_feedback',
            field=models.TextField(blank=True, help_text='Feedback or notes about the current status (e.g., reason for decline, information required)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('opened', 'Opened'), ('under_review', 'Under Review'), ('further_info_required', 'Further Information Required'), ('credit_check', 'Credit Check/Underwriting'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('opened', 'Opened'), ('under_review', 'Under Review'), ('further_info_required', 'Further Information Required'), ('credit_check', 'Credit Check/Underwriting'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this status change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
