# Generated by Django 4.1.13 on 2026-01-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Whether this document is required for the application'),
        ),
        migrations.CreateModel(
            name='ApplicationUnderwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(blank=True, help_text='Overall risk score (0-100, lower is better)', null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('approve', 'Approve'), ('approve_with_conditions', 'Approve with Conditions'), ('refer', 'Refer for Manual Review'), ('decline', 'Decline')], max_length=50)),
                ('assessment_summary', models.TextField(blank=True, help_text='Summary of AI assessment')),
                ('key_findings', models.JSONField(blank=True, default=list, help_text='List of key findings from document analysis')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of application strengths')),
                ('concerns', models.JSONField(blank=True, default=list, help_text='List of concerns or risk factors')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for lender')),
                ('documents_analyzed', models.IntegerField(default=0)),
                ('documents_valid', models.IntegerField(default=0)),
                ('documents_invalid', models.IntegerField(default=0)),
                ('documents_pending', models.IntegerField(default=0)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(default='ai_system', help_text='System or user who performed the assessment', max_length=50)),
                ('assessment_data', models.JSONField(blank=True, default=dict, help_text='Full assessment data from AI system')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting', to='applications.application')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
