# Generated by Django 4.1.13 on 2026-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationdocument_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='borrower_consent_given',
            field=models.BooleanField(default=False, help_text='Whether borrower has given consent to share their information with the lender'),
        ),
        migrations.AddField(
            model_name='application',
            name='borrower_consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When borrower gave consent', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='borrower_consent_withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When borrower withdrew consent (if applicable)', null=True),
        ),
    ]
