# Generated by Django 4.1.13 on 2026-01-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('lenders', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwritingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrowerprofile')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenders.lenderprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
